### PR TITLE
Fix for Phaser 2.4.4+ (PIXI.Stage is undefined).

### PR DESCRIPTION
**Pull request by doggan**
https://github.com/englercj/phaser-debug/issues/9

### CODE REVIEW

**Comment by englercj** [comment]
The only way PIXI.Stage would not exist is if Phaser doesn't exist, or they don't use PIXI v2 anymore.

**Comment by photonstorm** [comment]
We definitely still use PIXI.Stage internally.

**Comment by doggan** [comment]
I'm definitely including phaser before this plugin. I added my notes and a simple repro case to the Issue (https://github.com/englercj/phaser-debug/issues/9). Also confirmed in console that PIXI.Stage is undefined.

**Comment by englercj** [comment]
:+1: Thanks for looking into this and for getting it fixed!

**Pull request merged**
